### ISSUE TITLE
Treesize Everything - PowerShell is in NonInteractive mode

### ISSUE THREAD

**Issue by Corsw** [freezscholte/Public-Ninja-Scripts#4]
Hi,

i am trying to use your treesize script with everything, but i keep getting this error code:

```
Result: SUCCESS Output: Action: Uitvoeren Treesize, Result: Success
Exception calling "ShouldContinue" with "2" argument(s): "Windows PowerShell is in NonInteractive mode. Read and Prompt functionality is not available."
The term 'Search-Everything' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
```

I tried to fix this by adding -Force to the search-Everything command, but that didnt fix this.Can you tell me what i am doing wrong here? 

And what kind of costum field do you use for the html table? WYSIWIG, or something else?

thanks in advance for your help.

**Comment by thereverendgreen** [comment]
I have the exact same issue. The script works perfectly on some devices and throws the same error as above on others. Great script btw, just need it to work on all devices. :)

**Comment by Corsw** [comment]
> I have the exact same issue. The script works perfectly on some devices and throws the same error as above on others. Great script btw, just need it to work on all devices. :)

unfortunately i havent managed to fix this, If you do please let me know :)

**Comment by freezscholte** [comment]
Add Import-Module PSEverything -Force before invoking the module in my tes env this issue does not occur anymore.
